// SPDX-License-Identifier: Apache-2.0
// SenseEdge Neural Network Weights (INT8)
// Auto-generated by ml/export_weights.py -- do not edit by hand
//
// Network: 8 inputs -> 16 hidden (ReLU) -> 4 outputs (argmax)
// Total parameters: 212
//
// Memory layout (matches nn_engine.v):
//   [  0..127] Layer 1 weights  (16 neurons x 8 inputs, row-major)
//   [128..143] Layer 1 biases   (16 values)
//   [144..207] Layer 2 weights  (4 neurons x 16 inputs, row-major)
//   [208..211] Layer 2 biases   (4 values)
//
// Load into hardware via Wishbone register SE_NN_WEIGHTS:
//   for (int i = 0; i < 212; i++)
//       reg_write(SE_NN_WEIGHTS, NN_WEIGHT(i, all_weights[i]));

#ifndef NN_WEIGHTS_H
#define NN_WEIGHTS_H

#include <stdint.h>

// Layer 1 weights: 16 neurons x 8 inputs (row-major)
// Address range: [0..127]
// Weight for neuron n, input i = layer1_weights[n * 8 + i]
static const int8_t layer1_weights[128] = {
      18,  -34,  -14,   41,  -54,  -64,   29,  -12,  // neuron  0
     -21,   24,  -21,  -21,   11,  -86,  -77,  -25,  // neuron  1
     -45,   14,  -41,  -63,   66,  -10,    3,  -64,  // neuron  2
     -39,  -54,  -64,   15,  -42,  -70,  -41,   44,  // neuron  3
      -1,  -47,   37,  -55,    9,  -88,  -60,    9,  // neuron  4
      51,   -2,  -11,  -15,  -70,  -42,  -26,   43,  // neuron  5
     -88, -121,   11,  -59,  -75,  -42,    7,  -30,  // neuron  6
     -38,  -14,   15,   44,  -21,   -8,  -50,  -54,  // neuron  7
     -31,   21,  -26,   12,  -27,  -90,  -23,    5,  // neuron  8
      -2,   70, -118,   37,    4,  -13,    4,  -89,  // neuron  9
       0,    9,   37,  -29,  -54,  -42,   23,   -1,  // neuron 10
     -24,   23,    4,   43,  -31,  -15,  -18,  -66,  // neuron 11
      13,   12,    0,  -11,  -63,  -19,  -15,  -36,  // neuron 12
     -15,   14,   64,  -32,  -29,  -39, -127,  -36,  // neuron 13
    -123,   74,    2,  -20,  -33, -104,   26,  -26,  // neuron 14
     -31,  -72,   78,  -66,   23,   67,  -45,  -52,  // neuron 15
};

// Layer 1 biases: 16 values
// Address range: [128..143]
static const int8_t layer1_biases[16] = {
     -51,    0,    0,  -46,    0,    5, -126,    0, -100,    0,  -14,    0,    0,  -39, -127,  -59
};

// Layer 2 weights: 4 neurons x 16 inputs (row-major)
// Address range: [144..207]
// Weight for neuron n, input i = layer2_weights[n * 16 + i]
static const int8_t layer2_weights[64] = {
     -95,  -20,  -61,    4,  -42,   55,  -55,   61, -127,  -13,   21,  -48,    9,  -39, -119,    0,  // neuron 0
      -6,   31,  -48,  -41,   20,   14,  -14,   14,   37,    9,  -18,  -28,   73,   44,   76,   36,  // neuron 1
      23,   31,   45,  -33,   38,  -23,   12,   74,   14,  -29,   14,  -32,   -3,   71,  -89,   58,  // neuron 2
      54,   57,  -10,   96,   24,  -34,   21,   19,    0,   28,    9,   -3,  -33,  -53,   17,    5,  // neuron 3
};

// Layer 2 biases: 4 values
// Address range: [208..211]
static const int8_t layer2_biases[4] = {
    -127,   75,  -18,   70
};

// All 212 parameters in flat array for sequential weight loading
// Layout: L1 weights[128] | L1 biases[16] | L2 weights[64] | L2 biases[4]
// Load via: for (int i = 0; i < 212; i++)
//               reg_write(SE_NN_WEIGHTS, NN_WEIGHT(i, all_weights[i]));
static const int8_t all_weights[212] = {
    // Layer 1 weights [0..127]
      18,  -34,  -14,   41,  -54,  -64,   29,  -12,  -21,   24,  -21,  -21,   11,  -86,  -77,  -25,
     -45,   14,  -41,  -63,   66,  -10,    3,  -64,  -39,  -54,  -64,   15,  -42,  -70,  -41,   44,
      -1,  -47,   37,  -55,    9,  -88,  -60,    9,   51,   -2,  -11,  -15,  -70,  -42,  -26,   43,
     -88, -121,   11,  -59,  -75,  -42,    7,  -30,  -38,  -14,   15,   44,  -21,   -8,  -50,  -54,
     -31,   21,  -26,   12,  -27,  -90,  -23,    5,   -2,   70, -118,   37,    4,  -13,    4,  -89,
       0,    9,   37,  -29,  -54,  -42,   23,   -1,  -24,   23,    4,   43,  -31,  -15,  -18,  -66,
      13,   12,    0,  -11,  -63,  -19,  -15,  -36,  -15,   14,   64,  -32,  -29,  -39, -127,  -36,
    -123,   74,    2,  -20,  -33, -104,   26,  -26,  -31,  -72,   78,  -66,   23,   67,  -45,  -52,
    // Layer 1 biases [128..143]
     -51,    0,    0,  -46,    0,    5, -126,    0, -100,    0,  -14,    0,    0,  -39, -127,  -59,
    // Layer 2 weights [144..207]
     -95,  -20,  -61,    4,  -42,   55,  -55,   61, -127,  -13,   21,  -48,    9,  -39, -119,    0,
      -6,   31,  -48,  -41,   20,   14,  -14,   14,   37,    9,  -18,  -28,   73,   44,   76,   36,
      23,   31,   45,  -33,   38,  -23,   12,   74,   14,  -29,   14,  -32,   -3,   71,  -89,   58,
      54,   57,  -10,   96,   24,  -34,   21,   19,    0,   28,    9,   -3,  -33,  -53,   17,    5,
    // Layer 2 biases [208..211]
    -127,   75,  -18,   70
};

#endif // NN_WEIGHTS_H
